# Generated by Django 5.0.6 on 2024-05-21 11:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('content', models.TextField(verbose_name='Содержание события')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2024, 5, 21, 11, 31, 7, 279366, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
